"""
Family Group Sheet generation.

Creates standard genealogy family group sheets.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Literal

from genealogy_assistant.core.models import Person, Family, Event, Source


@dataclass
class FamilyGroupSheet:
    """
    Generates family group sheets.

    Family group sheets are a standard genealogical form documenting
    a nuclear family unit with sources for each fact.
    """

    family: Family
    husband: Person | None = None
    wife: Person | None = None
    children: list[Person] = field(default_factory=list)

    # Report settings
    title: str = "Family Group Sheet"
    researcher: str = ""
    date: datetime = field(default_factory=datetime.now)
    format: Literal["markdown", "html"] = "markdown"

    # Source references
    sources: list[Source] = field(default_factory=list)

    def generate(self) -> str:
        """Generate the family group sheet."""
        if self.format == "markdown":
            return self._generate_markdown()
        elif self.format == "html":
            return self._generate_html()
        else:
            raise NotImplementedError(f"Format {self.format} not supported")

    def _generate_markdown(self) -> str:
        """Generate Markdown format report."""
        lines = []

        # Header
        lines.append(f"# {self.title}")
        lines.append("")
        lines.append(f"**Prepared by:** {self.researcher or 'Unknown'}")
        lines.append(f"**Date:** {self.date.strftime('%d %B %Y')}")
        lines.append("")
        lines.append("---")
        lines.append("")

        # Husband
        lines.append("## Husband")
        lines.append("")
        if self.husband:
            lines.extend(self._format_person_details(self.husband))
        else:
            lines.append("*Unknown*")
        lines.append("")

        # Wife
        lines.append("## Wife")
        lines.append("")
        if self.wife:
            lines.extend(self._format_person_details(self.wife))
        else:
            lines.append("*Unknown*")
        lines.append("")

        # Marriage Information
        lines.append("## Marriage")
        lines.append("")
        if self.family.marriage:
            lines.extend(self._format_event(self.family.marriage, "Marriage"))
        else:
            lines.append("*No marriage record*")
        lines.append("")

        # Children
        lines.append("## Children")
        lines.append("")
        if self.children:
            lines.append("| # | Name | Birth | Death | Spouse |")
            lines.append("|---|------|-------|-------|--------|")

            for i, child in enumerate(self.children, 1):
                name = child.primary_name.full_name() if child.primary_name else "Unknown"
                birth = self._format_event_short(child.birth) if child.birth else "-"
                death = self._format_event_short(child.death) if child.death else "-"
                spouse = "-"  # Would need to look up marriages

                lines.append(f"| {i} | {name} | {birth} | {death} | {spouse} |")
        else:
            lines.append("*No children recorded*")
        lines.append("")

        # Detailed Children Section
        if self.children:
            lines.append("### Children Details")
            lines.append("")
            for i, child in enumerate(self.children, 1):
                name = child.primary_name.full_name() if child.primary_name else "Unknown"
                lines.append(f"#### Child {i}: {name}")
                lines.append("")
                lines.extend(self._format_person_details(child))
                lines.append("")

        # Sources
        lines.append("## Sources")
        lines.append("")
        if self.sources:
            for i, source in enumerate(self.sources, 1):
                lines.append(f"{i}. {self._format_source(source)}")
        else:
            lines.append("*No sources documented*")
        lines.append("")

        # Notes
        if self.family.notes:
            lines.append("## Notes")
            lines.append("")
            for note in self.family.notes:
                lines.append(f"- {note}")
            lines.append("")

        # Footer
        lines.append("---")
        lines.append("")
        lines.append("*Family Group Sheet generated by Genealogy Research Assistant*")

        return "\n".join(lines)

    def _format_person_details(self, person: Person) -> list[str]:
        """Format detailed person information."""
        lines = []

        # Name
        if person.primary_name:
            lines.append(f"**Full Name:** {person.primary_name.full_name()}")
            if person.primary_name.variants:
                lines.append(f"**Name Variants:** {', '.join(person.primary_name.variants)}")
        else:
            lines.append("**Full Name:** Unknown")

        # Vital Events
        if person.birth:
            lines.extend(self._format_event(person.birth, "Birth"))

        if person.christening:
            lines.extend(self._format_event(person.christening, "Christening"))

        if person.death:
            lines.extend(self._format_event(person.death, "Death"))

        if person.burial:
            lines.extend(self._format_event(person.burial, "Burial"))

        # Other Events
        for event in person.events:
            if event.event_type not in ("BIRT", "CHR", "DEAT", "BURI"):
                lines.extend(self._format_event(event, event.event_type))

        # Occupation
        if person.occupation:
            lines.append(f"**Occupation:** {person.occupation}")

        return lines

    def _format_event(self, event: Event, label: str) -> list[str]:
        """Format an event with full details."""
        lines = []

        date_str = event.date.to_gedcom() if event.date else "Unknown"
        place_str = event.place.name if event.place else "Unknown"

        lines.append(f"**{label}:** {date_str}")
        lines.append(f"**{label} Place:** {place_str}")

        if event.sources:
            source_refs = ", ".join(f"[{s}]" for s in event.sources)
            lines.append(f"**Source:** {source_refs}")

        return lines

    def _format_event_short(self, event: Event) -> str:
        """Format an event in short form for tables."""
        parts = []
        if event.date:
            parts.append(event.date.to_gedcom())
        if event.place:
            # Just city/town
            place_parts = event.place.name.split(",")
            parts.append(place_parts[0].strip())
        return ", ".join(parts) if parts else "-"

    def _format_source(self, source: Source) -> str:
        """Format a source citation."""
        parts = []

        if source.author:
            parts.append(source.author)
        if source.title:
            parts.append(f"*{source.title}*")
        if source.publisher:
            parts.append(f"({source.publisher})")
        if source.repository:
            parts.append(f"Repository: {source.repository}")
        if source.call_number:
            parts.append(f"Call #: {source.call_number}")

        return ", ".join(parts) if parts else "Unknown source"

    def _generate_html(self) -> str:
        """Generate HTML format report."""
        md = self._generate_markdown()

        # Convert markdown to basic HTML
        import re
        html_body = md
        html_body = re.sub(r'^#### (.+)$', r'<h4>\1</h4>', html_body, flags=re.MULTILINE)
        html_body = re.sub(r'^### (.+)$', r'<h3>\1</h3>', html_body, flags=re.MULTILINE)
        html_body = re.sub(r'^## (.+)$', r'<h2>\1</h2>', html_body, flags=re.MULTILINE)
        html_body = re.sub(r'^# (.+)$', r'<h1>\1</h1>', html_body, flags=re.MULTILINE)
        html_body = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html_body)
        html_body = re.sub(r'\*(.+?)\*', r'<em>\1</em>', html_body)
        html_body = re.sub(r'^---$', r'<hr>', html_body, flags=re.MULTILINE)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{self.title}</title>
    <style>
        body {{
            font-family: Georgia, serif;
            max-width: 800px;
            margin: 0 auto;
            padding: 2rem;
        }}
        table {{
            border-collapse: collapse;
            width: 100%;
            margin: 1rem 0;
        }}
        th, td {{
            border: 1px solid #333;
            padding: 8px;
            text-align: left;
        }}
        th {{
            background-color: #f0f0f0;
        }}
        h1 {{
            text-align: center;
            border-bottom: 2px solid #333;
            padding-bottom: 0.5rem;
        }}
        h2 {{
            background-color: #333;
            color: white;
            padding: 0.5rem;
            margin-top: 2rem;
        }}
    </style>
</head>
<body>
    {html_body}
</body>
</html>"""

    def save(self, path: str | Path) -> None:
        """Save report to file."""
        path = Path(path)
        content = self.generate()

        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
