"""
Pedigree Chart generation.

Creates ancestor pedigree charts in various formats.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Literal

from genealogy_assistant.core.models import Person


@dataclass
class PedigreeChart:
    """
    Generates pedigree (ancestor) charts.

    A pedigree chart shows the direct ancestors of an individual,
    typically in a standardized tree format.
    """

    subject: Person
    generations: int = 4  # Number of generations to show

    # Ancestor data (indexed by Ahnentafel number)
    # 1 = subject, 2 = father, 3 = mother, 4 = paternal grandfather, etc.
    ancestors: dict[int, Person] = field(default_factory=dict)

    # Report settings
    title: str = "Pedigree Chart"
    researcher: str = ""
    date: datetime = field(default_factory=datetime.now)
    format: Literal["markdown", "text", "html", "mermaid"] = "markdown"

    def __post_init__(self):
        """Initialize with subject at position 1."""
        if 1 not in self.ancestors:
            self.ancestors[1] = self.subject

    def add_ancestor(self, ahnentafel: int, person: Person) -> None:
        """Add an ancestor at the specified Ahnentafel number."""
        self.ancestors[ahnentafel] = person

    def get_father(self, ahnentafel: int) -> Person | None:
        """Get father of person at Ahnentafel number."""
        return self.ancestors.get(ahnentafel * 2)

    def get_mother(self, ahnentafel: int) -> Person | None:
        """Get mother of person at Ahnentafel number."""
        return self.ancestors.get(ahnentafel * 2 + 1)

    def generate(self) -> str:
        """Generate the pedigree chart."""
        if self.format == "markdown":
            return self._generate_markdown()
        elif self.format == "text":
            return self._generate_text()
        elif self.format == "html":
            return self._generate_html()
        elif self.format == "mermaid":
            return self._generate_mermaid()
        else:
            raise NotImplementedError(f"Format {self.format} not supported")

    def _generate_markdown(self) -> str:
        """Generate Markdown format chart."""
        lines = []

        # Header
        lines.append(f"# {self.title}")
        lines.append("")
        lines.append(f"**Subject:** {self._format_name(self.subject)}")
        lines.append(f"**Prepared by:** {self.researcher or 'Unknown'}")
        lines.append(f"**Date:** {self.date.strftime('%d %B %Y')}")
        lines.append(f"**Generations:** {self.generations}")
        lines.append("")
        lines.append("---")
        lines.append("")

        # Ahnentafel Table
        lines.append("## Ahnentafel List")
        lines.append("")
        lines.append("| # | Relationship | Name | Birth | Death |")
        lines.append("|---|--------------|------|-------|-------|")

        max_num = 2 ** self.generations - 1
        for num in range(1, max_num + 1):
            person = self.ancestors.get(num)
            rel = self._get_relationship(num)

            if person:
                name = self._format_name(person)
                birth = person.birth.date.to_gedcom() if person.birth and person.birth.date else "-"
                death = person.death.date.to_gedcom() if person.death and person.death.date else "-"
            else:
                name = "*Unknown*"
                birth = "-"
                death = "-"

            lines.append(f"| {num} | {rel} | {name} | {birth} | {death} |")

        lines.append("")

        # Text Tree
        lines.append("## Pedigree Tree")
        lines.append("")
        lines.append("```")
        lines.extend(self._generate_tree_lines())
        lines.append("```")
        lines.append("")

        # Statistics
        lines.append("## Statistics")
        lines.append("")
        total_slots = 2 ** self.generations - 1
        filled_slots = len(self.ancestors)
        lines.append(f"- **Total ancestor slots:** {total_slots}")
        lines.append(f"- **Filled slots:** {filled_slots}")
        lines.append(f"- **Completion:** {filled_slots / total_slots * 100:.1f}%")
        lines.append("")

        # Missing ancestors by generation
        lines.append("### Missing Ancestors by Generation")
        lines.append("")
        for gen in range(1, self.generations + 1):
            start = 2 ** (gen - 1)
            end = 2 ** gen
            missing = sum(1 for i in range(start, end) if i not in self.ancestors)
            total = end - start
            lines.append(f"- Generation {gen}: {missing}/{total} missing")

        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("*Pedigree chart generated by Genealogy Research Assistant*")

        return "\n".join(lines)

    def _generate_text(self) -> str:
        """Generate plain text tree."""
        lines = [
            self.title,
            "=" * len(self.title),
            "",
        ]
        lines.extend(self._generate_tree_lines())
        return "\n".join(lines)

    def _generate_tree_lines(self) -> list[str]:
        """Generate ASCII tree representation."""
        lines = []

        # Simple 4-generation layout
        def person_str(num: int, width: int = 30) -> str:
            person = self.ancestors.get(num)
            if person:
                name = self._format_name(person)
                if len(name) > width - 2:
                    name = name[:width - 5] + "..."
                return f"[{name}]"
            return f"[{'?' * (width - 2)}]"

        if self.generations >= 1:
            # Subject
            lines.append(f"1. {person_str(1)}")

        if self.generations >= 2:
            lines.append("    |")
            lines.append("    +-- 2. " + person_str(2))  # Father
            lines.append("    |")
            lines.append("    +-- 3. " + person_str(3))  # Mother

        if self.generations >= 3:
            lines.append("         |")
            lines.append("         +-- 4. " + person_str(4))  # Paternal GF
            lines.append("         +-- 5. " + person_str(5))  # Paternal GM
            lines.append("         |")
            lines.append("         +-- 6. " + person_str(6))  # Maternal GF
            lines.append("         +-- 7. " + person_str(7))  # Maternal GM

        if self.generations >= 4:
            lines.append("              |")
            lines.append("              +-- 8-15. Great-grandparents")
            for i in range(8, 16):
                person = self.ancestors.get(i)
                if person:
                    lines.append(f"                  {i}. {self._format_name(person)}")

        return lines

    def _generate_mermaid(self) -> str:
        """Generate Mermaid diagram code."""
        lines = [
            "```mermaid",
            "graph TD",
        ]

        # Add nodes
        for num, person in self.ancestors.items():
            name = self._format_name(person).replace('"', "'")
            lines.append(f'    P{num}["{num}. {name}"]')

        # Add relationships
        max_num = 2 ** self.generations - 1
        for num in range(1, (max_num + 1) // 2):
            father_num = num * 2
            mother_num = num * 2 + 1

            if father_num in self.ancestors:
                lines.append(f"    P{father_num} --> P{num}")
            if mother_num in self.ancestors:
                lines.append(f"    P{mother_num} --> P{num}")

        lines.append("```")

        return "\n".join(lines)

    def _generate_html(self) -> str:
        """Generate HTML format chart."""
        md = self._generate_markdown()

        import re
        html_body = md
        html_body = re.sub(r'^### (.+)$', r'<h3>\1</h3>', html_body, flags=re.MULTILINE)
        html_body = re.sub(r'^## (.+)$', r'<h2>\1</h2>', html_body, flags=re.MULTILINE)
        html_body = re.sub(r'^# (.+)$', r'<h1>\1</h1>', html_body, flags=re.MULTILINE)
        html_body = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html_body)
        html_body = re.sub(r'\*(.+?)\*', r'<em>\1</em>', html_body)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{self.title}</title>
    <style>
        body {{ font-family: Arial, sans-serif; max-width: 900px; margin: 0 auto; padding: 2rem; }}
        table {{ border-collapse: collapse; width: 100%; }}
        th, td {{ border: 1px solid #ddd; padding: 8px; }}
        th {{ background-color: #4CAF50; color: white; }}
        pre {{ background-color: #f4f4f4; padding: 1rem; overflow-x: auto; }}
    </style>
</head>
<body>
    {html_body}
</body>
</html>"""

    def _format_name(self, person: Person) -> str:
        """Format person name."""
        if person.primary_name:
            return person.primary_name.full_name()
        return "Unknown"

    def _get_relationship(self, ahnentafel: int) -> str:
        """Get relationship description from Ahnentafel number."""
        relationships = {
            1: "Subject",
            2: "Father",
            3: "Mother",
            4: "Paternal Grandfather",
            5: "Paternal Grandmother",
            6: "Maternal Grandfather",
            7: "Maternal Grandmother",
        }

        if ahnentafel in relationships:
            return relationships[ahnentafel]

        # Calculate generation and position
        import math
        gen = int(math.log2(ahnentafel)) + 1

        if gen == 4:
            prefix = {8: "Pat-Pat", 9: "Pat-Pat", 10: "Pat-Mat", 11: "Pat-Mat",
                     12: "Mat-Pat", 13: "Mat-Pat", 14: "Mat-Mat", 15: "Mat-Mat"}
            suffix = "Grandfather" if ahnentafel % 2 == 0 else "Grandmother"
            return f"{prefix.get(ahnentafel, '')} Great-{suffix}"

        greats = gen - 2
        great_prefix = "Great-" * greats
        suffix = "Grandfather" if ahnentafel % 2 == 0 else "Grandmother"
        return f"{great_prefix}{suffix}"

    def save(self, path: str | Path) -> None:
        """Save chart to file."""
        path = Path(path)
        content = self.generate()

        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
